### PR TITLE
Update Vercel deployment documentation.

### PR DESCRIPTION
**Pull request by leerob**
Ensures documentation reflects Nuxt 3 being zero configuration on Vercel, and includes example command to scaffold application. This also adds translations for other languages (please correct any translations if not 100% accurate).

### CODE REVIEW

**Comment by smarroufin** [comment]
Hi @leerob 
Thanks for the contribution, but this is the Nuxt v2 repo/docs over here :disappointed: 
If you want to add more details to the Nuxt v3 docs:
https://v3.nuxtjs.org/docs/deployment/vercel -> https://github.com/nuxt/framework/blob/main/docs/content/3.docs/3.deployment/6.vercel.md

By the way, you are not required to make a PR with all languages translated. I guess the french part has been google translated and you better not translate it in that case and let a french contributor handle it :wink:

**Comment by leerob** [comment]
I made a PR there as well! https://github.com/nuxt/framework/pull/3000

**Comment by smarroufin** [comment]
Thank you! Closing this one then.

**Comment by leerob** [comment]
Can we not still update the v2 docs?

**Pull request closed without merging**
