### PR TITLE
Switch from `node-sass` to `sass`

### PR DESCRIPTION
**Pull request by MartijnCuppens**
Dart sass (`sass`) is the primary implementation of Sass, is more lightweight and is maintained a little better.

Also, `sass-loader` recommends the usage of `sass`:
https://www.npmjs.com/package/sass-loader

### CODE REVIEW

**Comment by danielroe** [comment]
I'd recommend installing `fibers` in this case for better performance.

**Comment by Atinux** [comment]
What would be the example using `fibers`  @danielroe ?

**Comment by danielroe** [comment]
@atinux nothing needs to be done to use `fibers` other than to have it installed in your dependencies. So it would just mean adding this line in each case where `sass` is installed:

```
(It is also recommended to install `fibers` as a devDependency to speed up CSS compilation.)
```

Or, more strongly, you could simply amend the install commands to (for example):
```
 npm install --save-dev sass sass-loader fibers
```

**Comment by Atinux** [comment]
Thanks @danielroe 

I think we can directly suggest:

```bash
npm install --save-dev sass sass-loader fibers
```

And stating that `fibers` is aimed to speed up the compilation process.

Do you mind updating it @MartijnCuppens ?

**Comment by MartijnCuppens** [comment]
> Do you mind updating it @MartijnCuppens ?

Of course not. I've just added `fibers`.

**Comment by debs-obrien** [comment]
Thanks guys 😃

**Review by debs-obrien — APPROVED** [review]

**Review by febrihidayan — APPROVED** [review]

**Comment by mrleblanc101** [comment]
The fibers documentation did not help me understand why it was needed, but sass docs mention this package.
Maybe some explaination of why fibers is needed should be added to the Nuxt docs too.

**Pull request merged**
