### PR TITLE
docs(zh): Update translation Chinese example

### PR DESCRIPTION
**Pull request by thedb**
zh.nuxtjs.org has not been updated for a long time, I will use my free time to update the latest Chinese documents

Some new examples have been translated this time

### CODE REVIEW

**Comment by thedb** [comment]
Every guys, happy Christmas~
也祝中国的程序员们早点下班~

**Comment by thedb** [comment]
All examples have been updated to the latest translated version.
Next, I will translate other documents.
Please merge to the main branch.

**Comment by thedb** [comment]
> fantastic. great work. thanks.😃

thx，but i found some problems..

In the [examples](https://zh.nuxtjs.org/examples/hello-world) path, the navigation on the left has been updated to the latest version, but the content on the right is still in English, but my code has been merged successfully. What is wrong with the configuration Is it

**Comment by debs-obrien** [comment]
yes if I remember correctly we need to add it to the array of languages in the examples slug page so it shows that Language and not english. I can sort it later if you don't see it.

**Comment by thedb** [comment]
> yes if I remember correctly we need to add it to the array of languages in the examples slug page so it shows that Language and not english. I can sort it later if you don't see it.

I found the keyword `app.i18n.defaultLocale` in the `page/example/_slug` directory, but after I modified it in `nuxt.config.js`, there seemed to be a lot of problems when compiling...

And i also tried to sort the array of `i18n.locales`, it seems only affects the options on the homepage. 

Maybe i need your help XD

**Comment by debs-obrien** [comment]
Hi @thedb I just fixed the examples by adding 'zh' to array - https://github.com/nuxt/nuxtjs.org/pull/1131 seems to be working fine but for sure if you see any issues just let me know.

**Comment by thedb** [comment]
> Hi @thedb I just fixed the examples by adding 'zh' to array - #1131 seems to be working fine but for sure if you see any issues just let me know.

Yes，It still have problems.
No problem with first entry  [examples](https://zh.nuxtjs.org/examples) path, but when I click on the sidebar, the English translation is still displayed. No Chinese translation displayed.

**Comment by thedb** [comment]
> should be fixed now @thedb

No problem now! Very grateful for your help! 
Recently, my work is a bit busy, but I will continue to complete the remaining Chinese translation XD

**Comment by whwh1233** [comment]
I hope to join you and continue the Chinese translation of Nuxt.js documents. Are there any pages that have not been translated yet?

**Pull request merged**
