### PR TITLE
Using mousetrap to focus on search input field via '/' #233

### PR DESCRIPTION
**Pull request by thiyagu-7**
Added mousetrap via yarn (`yarn add mousetrap`). 
Bound `/` to focus on the text field.
Tested in chrome, firefox and safari.

---

How should I go about changing the seach text? I see that they are in a separate repo
https://github.com/nuxt/docs

Shall I send a PR for that? How should translations be handled?

### CODE REVIEW

**Comment by Atinux** [comment]
Thank you @thiyagu-7 

Indeed for the text it's directly inside the nuxt/docs repo, you can open a PR there :)

**Comment by thiyagu-7** [comment]
@Atinux Thanks for merging my changes. Regd the docs, I can update the [en/lang.json](https://github.com/nuxt/docs/blob/master/en/lang.json). How would the other language translations be handled normally?

**Comment by Atinux** [comment]
If you add a field, it will have to be added to the other `lang.json` file in the other folders

**Comment by thiyagu-7** [comment]
@Atinux Here, I'll be changing the placeholder text, to include that the quick search shortcut is available.

The [readme of the docs repo](https://github.com/nuxt/docs) states the translations are handled by certain persons. So, I was wondering how should I update the other lang folders?

**Comment by thiyagu-7** [comment]
@Atinux Thanks. Opened a [PR](https://github.com/nuxt/docs/pull/1607) for that.

**Pull request merged**
