### PR TITLE
[doc] $http is not directly accessible from context

### PR DESCRIPTION
**Pull request by Wolvborg**
Changed $http to app.$http

### CODE REVIEW

**Comment by Wolvborg** [comment]
Will be my first contribution for an open source :p(though very tiny)

**Comment by Wolvborg** [comment]
@Atinux  can you please approve

**Review by danielroe — COMMENTED** [review]
@Wolvborg What makes you think that `$http` isn't directly accessible from context?

https://codesandbox.io/s/blissful-darkness-5r2m5?file=/pages/index.vue

If it's not showing up on the types, then would you raise an issue [here](https://github.com/nuxt/http/issues) instead?

**Comment by Wolvborg** [comment]
@danielroe It is written in the docs that context consist followings keys

image


Also in the same page(https://nuxtjs.org/docs/concepts/context-helpers), we are accessing `$http` from `app`, so how we can destructure `$http` from `context`. 
image


This is typo error in docs and not in the actual code 
image

**Comment by danielroe** [comment]
@Wolvborg It is accessible through both `context.$http` and `context.app.$http`. Here is the [documentation for the http module](https://http.nuxtjs.org/getting-started/usage#using-in-asyncdata).

If it's helpful, here's [some information](https://nuxtjs.org/docs/directory-structure/plugins/#inject-in-root--context) on what 'inject' does if you are injecting your own values into context.

**Pull request closed without merging**
