### PR TITLE
Update Guides/Get Started in Bahasa Indonesia

### PR DESCRIPTION
**Pull request by andriannus**
Hi, I'm Andre from Indonesia.
I'm very happy with Nuxt.js ❤
I've read the Documentation in Bahasa Indonesia. I found a lot of sentences that looked stiff. I hope this helps.
I will also help translate other pages that have not yet been translated into Indonesian. Wait for my other Pull Request.

Thank you.

Regards,
Andre

Bdw, I have another Pull Request too for Updating the Routing Pages. I hope is not a spam. #516 😀

### CODE REVIEW

**Comment by debs-obrien** [comment]
great, thanks. yes feel free to keep improving them. that would be great

**Comment by febrihidayan** [comment]
@andriannus kerja bagus Andre, Saya harap Anda selalu bersemangat 👏. Ada sedikit saran dari saya, untuk kata skrip seharusnya tidak diganti dengan script. Saya juga berfikir akan membuat kata script sebelumnya. Tapi script bisa mengacu dua hal antara kata dan tag script.
Thanks 😀

**Comment by andriannus** [comment]
@febrihidayan Wah, betul juga ya, Mas. Maaf. Noted untukku, ya. Aku coba perbaiki ya, Mas.. Ayo kita buat dokumentasi Bahasa Indonesianya. 😄

**Comment by febrihidayan** [comment]
@andriannus hahaha!, lanjutkan mas 👏. Saya akan melakukannya di hari libur 🤣

**Pull request merged**
