### PR TITLE
[WIP] Docs translations to brazilian portuguese (pt-BR)

### PR DESCRIPTION
**Pull request by oiagorodrigues**
I've started the translations of the docs to brazilian portuguese.

#### i18n configuration

- [x] i18n file

- [x] i18n block on nuxt.config

#### 📝 guides -> components glossary

- [x] pages-fetch.md

- [x] pages-head.md

- [x] pages-key.md

- [x] pages-layout.md

- [x] pages-loading.md

- [x] pages-middleware.md

- [x] pages-scrolltotop.md

- [x] pages-transition.md

- [x] pages-validate.md

- [x] pages-watchquery.md

#### 📝 guides -> concepts

- [x] context-helpers.md

- [x] nuxt-lifecycle.md

- [x] server-side-rendering.md

- [x] static-site-generation.md

- [x] views.md

#### 📝 guides -> configuration glossary

- [x] configuration-build.md

- [x] configuration-generate.md
- [x] configuration-render.md
- [x] configuration-server.md
- [x] configuration-telemetry.md
- [x] configuration-router.md
- [x] configuration-server-middleware.md
- [x] configuration-transition.md
- [x] configuration-builddir.md

- [x] configuration-cli.md

- [x] configuration-components.md

- [x] configuration-css.md

- [x] configuration-dev.md

- [x] configuration-dir.md

- [x] configuration-env.md

- [x] configuration-extend-plugins.md

- [x] configuration-global-name.md

- [x] configuration-head.md

- [x] configuration-hooks.md

- [x] configuration-ignore.md

- [x] configuration-loading.md

- [x] configuration-loading-indicator.md

- [x] configuration-mode.md

- [x] configuration-modern.md

- [x] configuration-modules.md

- [x] configuration-modulesdir.md

- [x] configuration-plugins.md

- [x] configuration-rootdir.md

- [x] configuration-runtime-config.md

- [x] configuration-srcdir.md

- [x] configuration-target.md

- [x] configuration-vue-config.md

- [x] configuration-watch.md

- [x] configuration-watchers.md

#### 📝 guides -> directory structure

- [x] assets.md

- [x] components.md

- [x] content.md

- [x] dist.md

- [x] layouts.md

- [x] middleware.md

- [x] modules.md

- [x] nuxt.md

- [x] nuxt-config.md

- [x] pages.md

- [x] plugins.md

- [x] static.md

- [x] store.md

#### 📝 guides -> features

- [x] configuration.md

- [x] data-fetching.md

- [x] deployment-targets.md

- [x] file-system-routing.md

- [x] live-preview.md

- [x] loading.md

- [x] meta-tags-seo.md

- [x] nuxt-components.md

- [x] rendering-modes.md

- [x] transitions.md

#### 📝 guides -> get-started

- [x] conclusion.md

- [x] directory-structure.md

- [x] installation.md

- [x] routing.md

- [x] upgrading.md

#### 📝 guides -> internals glossary

- [x] $nuxt.md

- [x] context.md

- [x] internals.md

- [x] internals-builder.md

- [x] internals-generator.md

- [x] internals-module-container.md

- [x] internals-nuxt.md

- [x] internals-renderer.md

- [x] nuxt.md

- [x] nuxt-render.md

- [x] nuxt-render-and-get-window.md

- [x] nuxt-render-route.md

### CODE REVIEW

**Comment by debs-obrien** [comment]
Nice work. nicely organised too. 😍

**Comment by oiagorodrigues** [comment]
Thanks @debs-obrien. Doing my best 😝

**Comment by oiagorodrigues** [comment]
@debs-obrien the [guides](https://nuxtjs.org/guides/get-started/installation) section and the i18n properties are all translated. Ready for review.

**Comment by debs-obrien** [comment]
Amazing work 💪. thank you so much for your contribution. will merge this and then check with team on setting up the sub domain to see if anything else is missing.

**Pull request merged**
