### PR TITLE
[Translation] Portuguese

### PR DESCRIPTION
**Pull request by BrendonHenrique**
Hey ! 
I just get started on portuguese translations, I have already sync translations on the following files : 

- [x] content/pt/docs/index.md
- [x] content/pt/docs/1.get-started/index.md
- [x] content/pt/docs/1.get-started/1.installation.md  
- [x] content/pt/docs/1.get-started/2.routing.md
- [x] content/pt/docs/1.get-started/3.directory-structure.md
- [x] content/pt/docs/1.get-started/4.commands.md
- [x] content/pt/docs/1.get-started/5.conclusion.md
- [x] content/pt/docs/1.get-started/6.upgrading

Obs: very glad to help out with this amazing tool ! Nuxt have been helping me for a long while, and I just want to make sure that everyone from brasil or other portuguese based languages countries can experience this as well !

### CODE REVIEW

**Comment by BrendonHenrique** [comment]
oh yeah thats make sense ! 
I tried to see the pages and yeah there's no fallback, I got broken pages. 
no worries ! I'm gonna get all those missed files !

**Comment by BrendonHenrique** [comment]
hey @smarroufin 
I just added every md files that exists in content/en and was missing, updated forked branch with last updates on nuxt:main, and added more few docs ( done with content/pt/docs/1.get-started ).

**Comment by BrendonHenrique** [comment]
no problems ! 
so I've just updated the content/pt folder as well, just to get sync with these last fixes 😀

**Comment by nazarepiedady** [comment]
Okay, I intend to be available to help update and maintain the Portuguese version of documentation.

**Pull request merged**
