### PR TITLE
Feat/modules link

### PR DESCRIPTION
**Pull request by debs-obrien**

### CODE REVIEW

**Comment by pi0** [comment]
@debs-obrien Correct way for PR title is `feat: modules link` :)

**Comment by debs-obrien** [comment]
ooops. how did that happen

**Comment by manniL** [comment]
We might want to introduce semantic pr bot here too (like we have in the core repo)

**Comment by pi0** [comment]
@manniL It is not essential i guess since docs don't have a changelog but would be nice if stick with it 😸

**Pull request merged**
