### PR TITLE
Update routing.md

### PR DESCRIPTION
**Pull request by katerlouis**
Vue suggests to you kebab-case for components.
The docs already do this here: https://nuxtjs.org/guides/features/file-system-routing and should be consistent in this.

### CODE REVIEW

**Comment by manniL** [comment]
> Vue suggests to you kebab-case for components.

Yes, but only when using DOM templates. In SFCs, `PascalCase` is recommended ([source](https://vuejs.org/v2/style-guide/#Component-name-casing-in-templates-strongly-recommended)). Thus, we decided to use `PascalCase` where appropriate. If there are inconsistencies, please feel free to send in a PR for them there.

**Review by manniL — CHANGES_REQUESTED** [review]
See comment above

**Comment by debs-obrien** [comment]
Hi @katerlouis thanks for your contribution. As @manniL stated PascalCase is recommenced for SFC and it is what we have decided to use as a standard thought our docs and code examples and site. It doesn't mean that you can't use kebab-case just that we are being consistent and only recommending one way of writing it to make things easier for people and will therefore recommend to use <NuxtLink> over <nuxt-link>. Hope that helps explain why it is this way in the docs. Reach out if you need further clarification.

**Comment by katerlouis** [comment]
Agreed. Created another PR for the different usage in the docs. :)

**Pull request closed without merging**
