### PR TITLE
fix: localhost link

### PR DESCRIPTION
**Pull request by debs-obrien**
markdown/content module doesn't like the http inside the link text so removed it so it works correctly

### CODE REVIEW

**Comment by debs-obrien** [comment]
@benjamincanac it seems that content module isn't allowing me to add the link text with http and have had to make this pr to fix broken markdown links. Are you aware of this behaviour. this pr fixes it but I am sure it was working properly before. If you need me to submit an issue to content let me know.

**Review by Atinux — APPROVED** [review]

**Comment by danielroe** [comment]
As promised :sparkles:

**Review by inouetakuya — APPROVED** [review]
LGTM, thank you! 👍

**Review by febrihidayan — APPROVED** [review]

**Comment by rexarvind** [comment]
Screenshot_2021-01-27-16-04-33-628

Its also on [your blog article](https://nuxtjs.org/blog/creating-blog-with-nuxt-content), and maybe at many more pages 😓

**Comment by pi0** [comment]
Hi @debs-obrien. Issue seems also happening with 2.14.12. Made https://github.com/nuxt/content/issues/737 with minimal reproduction for this.

**Comment by debs-obrien** [comment]
Ok cool. Thanks @pi0. I had reached out to Ben first but he told me it wasn't a content thing. Perhaps the error has been there longer than we thought 🤷‍♀️

**Comment by pi0** [comment]
There is a blackhole in node_modules 🤣 It might we one of sub dependencies updated with yarn.lock. 

If you know a commit that was fine, we may fallback yarn lock and compare what changed since

**Comment by AlexanderBelokon** [comment]
You're right, @pi0, it is a regression in one of sub dependencies, more specifically in [micromark-extension-gfm-autolink-literal @ 0.5.5](https://github.com/micromark/micromark-extension-gfm-autolink-literal/releases/tag/0.5.5). I've linked details in [your issue](https://github.com/nuxt/content/issues/737).

**Pull request merged**
