### PR TITLE
fix: update link to new website

### PR DESCRIPTION
**Pull request by taigrr**
See #2163

### CODE REVIEW

**Review by danielroe — APPROVED** [review]
thanks!

**Comment by awwaiid** [comment]
I don't know if it takes a while to get to production or what, but the current link on the nuxtjs.org site `https://nuxtjs.org/https:/nuxt.com/v3/`

**Comment by taigrr** [comment]
Yeah, it's probably waiting on an approval. The [deploy preview](https://deploy-preview-2164--nuxt.netlify.app/) for this PR is operating correctly.

**Comment by awwaiid** [comment]
Yes great -- confirmed that it is now fixed on production.

**Pull request merged**
