### PR TITLE
fix: link for module list

### PR DESCRIPTION
**Pull request by manniL**

### CODE REVIEW

**Comment by pi0** [comment]
@manniL Do you mind also updating https://github.com/nuxt/nuxtjs.org/blob/master/content/en/api/configuration-modules.md ?

**Comment by debs-obrien** [comment]
oh wow. am sure autosave or something auto added that as I didn't 😡
merging this to fix it and we can create a new pr for old docs if you still think it is necessary but I haven't been adding anything to old docs as they will be removed at end of month @pi0

**Comment by pi0** [comment]
@debs-obrien It will be 404? :O

**Comment by debs-obrien** [comment]
what will be a 404. tested it locally
https://github.com/nuxt/nuxtjs.org/pull/883

**Comment by pi0** [comment]
I meant link to old docs in one month :D (i guess not)

**Comment by debs-obrien** [comment]
ah we will fix that with redirects. it will be a lot of work but worth it as managing 2 sets of docs is a nightmare

**Pull request merged**
