### PR TITLE
Add HOST environmental variable with value 0.0.0.0

### PR DESCRIPTION
**Pull request by RecoX**
Add HOST environmental variable with value 0.0.0.0 fixes the issue here.

I have problems deploying to Digital Ocean, this is my ticket to help with them

I have a website that's made in Nuxt.js, I followed this guide:
https://nuxtjs.org/deployments/digital-ocean/#continuous-deployment-cd
```
If I use yarn build instead of npm run build, the build throws errors with NPM the build stage works fine.
In the deploy stage if I use the command npm run start --hostname 0.0.0.0 it throws an error
[2022-05-29 05:09:52]
[2022-05-29 05:09:52] > [argentum20@1.0.0](mailto:argentum20@1.0.0) start
[2022-05-29 05:09:52] > nuxt start "0.0.0.0"
[2022-05-29 05:09:52]
[2022-05-29 05:09:54]
[2022-05-29 05:09:54] FATAL No build files found in /workspace/0.0.0.0/.nuxt/dist/server.
[2022-05-29 05:09:54] Use either `nuxt build` or `builder.build()` or start nuxt in development mode.
[2022-05-29 05:09:54]
[2022-05-29 05:09:54] Use either `nuxt build` or `builder.build()` or start nuxt in development mode.
[2022-05-29 05:09:54] at VueRenderer._ready (node_modules/@nuxt/vue-renderer/dist/vue-renderer.js:758:13)
[2022-05-29 05:09:54] at async Server.ready (node_modules/@nuxt/server/dist/server.js:637:5)
[2022-05-29 05:09:54] at async Nuxt._init (node_modules/@nuxt/core/dist/core.js:482:7)
[2022-05-29 05:09:54]
[2022-05-29 05:09:54]
[2022-05-29 05:09:54] ╭──────────────────────────────────────────────────────────────────────────────╮│ ││ ✖ Nuxt Fatal Error ││ ││ Error: No build files found in /workspace/0.0.0.0/.nuxt/dist/server. ││ Use either `nuxt build` or `builder.build()` or start nuxt in ││ development mode. ││ │╰──────────────────────────────────────────────────────────────────────────────╯
[2022-05-29 05:09:54]
[2022-05-29 05:09:54] npm notice
[2022-05-29 05:09:54] npm notice New minor version of npm available! 8.1.0 -> 8.11.0
[2022-05-29 05:09:54] npm notice Changelog:
[2022-05-29 05:09:54] npm notice Run `npm install -g [npm@8.11.0](mailto:npm@8.11.0)` to update!
[2022-05-29 05:09:54] npm notice
[]
```
In the deploy stage, when I run npm run start instead then console looks like:
```
[2022-05-29 04:51:43]
[2022-05-29 04:51:43] > [argentum20@1.0.0](mailto:argentum20@1.0.0) start
[2022-05-29 04:51:43] > nuxt start
[2022-05-29 04:51:43]
[2022-05-29 04:51:46] ℹ Listening on: http://localhost:3000/
```

### CODE REVIEW

**Comment by danielroe** [comment]
I believe the issue you are experience is because, with `npm`, the command should be `npm run start -- --hostname 0.0.0.0`.

**Comment by RecoX** [comment]
> I believe the issue you are experiencing is because, with `npm`, the command should be `npm run start -- --hostname 0.0.0.0`.

I tried with npm run start --hostname 0.0.0.0

But it did not work because then digital ocean looks for files in the 0.0.0.0 folder

**Comment by danielroe** [comment]
@RecoX There is an additional `--` in the command I gave you.

**Comment by RecoX** [comment]
> @RecoX There is an additional `--` in the command I gave you.

Sure, but you should put that in the official documentation in case someone doesn't want or can't use yarn and needs to use npm otherwise is impossible to deploy.

**Pull request closed without merging**
